### ISSUE TITLE
Headlights not working properly in underground parking lot

### ISSUE THREAD

**Issue by MiesThies** [ThirteenAG/GTAIV.EFLC.FusionFix#123]
As the title says:
In the underground parking lot in Algonquin, close to Nikos apartment and the Police station, the headlights don't illuminate the surroundings, even though they are turned on, and they do work properly before driving in.

I don't know if this is known or fixable, just something I noticed.

![GTAIV_2023_08_05_02_32_10_878](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/74a81777-9ff2-4920-a534-2cd55d8e0ac1)
![GTAIV_2023_08_05_02_31_55_877](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/71256665-86ab-44e3-a837-c33f87fd108c)
![GTAIV_2023_08_05_02_32_05_673](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/90831279/b76767c2-66d3-49ff-b289-f728732c097b)

**Comment by sTc2201** [comment]
It's caused by the **MH8_carpark** timecycle modifier that is placed there. The MinFarClip and MaxFarClip key values seem to affect headlight rendering. You can just edit them yourself in the timecyclemodifiers.dat, set them to something higher than the default value of that modifier and that should fix it,.
I set both Min- and MaxFarClip to 300.0 in that screenshot below:

![a](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/41953894/17f872b2-e890-4e52-8572-be4f14661e40)

Also worth mentioning: This issue does not seem to occur in TBoGT, headlights render just fine there even when the modifier is active.

**Comment by MiesThies** [comment]
Cool, thanks for letting me know. I will try that out!
No wonder it works fine in TBoGT, since there's a whole mission set in that garage and the missing lighting must have occurred to the R* devs..

Anyway, it should also be an easy fix for the FF devs then :)

**Comment by Tomasak** [comment]
I cannot reproduce, it works fine on my side, timecyclemodifiers is untouched.
![Grand Theft Auto 4 Screenshot 2023 08 07 - 15 35 37 11](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/11007651/3d79c110-7c70-4cb8-8115-2fc0f1d512c8)

**Comment by sTc2201** [comment]
Only the high beam headlights seem to be working there and only at night or during raining/drizzle/lightning/foggy weather cycles. Neither high or low beam work during the day or any other weather, tested it myself on the CE and pre-CE build, same results. 
I assume you took that screenshot either at night or during rainy/foggy weather?

>...and the missing lighting must have occurred to the R* devs

Yeah, might be another hardcoded episode ID check just to fix this, but on the other hand Rockstar added more light sources to this parking lot through map files for TBoGT to combat this issue as well :^).

>Anyway, it should also be an easy fix for the FF devs then :)

Actually, I'm not sure if this fix should be included in FusionFix since it might be conflicting with other mods that use timecyclemodifiers so it would require extra editing from the user-side. It fits more into i.e Various Fixes or other mods that fix smaller details of the game.

**Comment by MiesThies** [comment]
Thanks for clarifying! 
I would love a FF fix, although I see your point with the mod compatibility.

Maybe it could be an optional fix, that is toggled “off” by default in the .ini😊

**Comment by Tomasak** [comment]
since its a vanilla bug, it should be reopened here https://github.com/GTAmodding/GTAIV-Issues-List/issues
