### ISSUE TITLE
[Feature Request] Better audio quality?

### ISSUE THREAD

**Issue by Void48** [ThirteenAG/GTAIV.EFLC.FusionFix#129]
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/85196642/74b5405b-ece4-4048-bd83-ed0111176fc6)

**Comment by Imflyin2023** [comment]
Very, and very unlikely, because this will increase the size of the Fusion FIx by more than 10 GB.

**Comment by nf555555** [comment]
Those resources could be a separate one time only download.

There is a Skyrim mod called the Unofficial High Definition Audio Project which replaces all of the low audio quality voices and music with the high quality versions from the PS4 release, using files directly ripped from the PS4 copy and converted from the PS4's .at9 format, so there's probably a way to rip PS3 audio files too. This Skyrim mod is 8.6GB if you download both the music and voices in the highest quality (sound effects are already high quality in the PC release). That's just for English, it's around 6.5GB more for each additional language.

**Comment by Tomasak** [comment]
This is out of scope for fusion fix. and as of now there are barely tools to export PC audio. Restored LCHC station from xbox360 used directly captured audio from emulation.

**Comment by Imflyin2023** [comment]
> This is out of scope for fusion fix. and as of now there are barely tools to export PC audio. Restored LCHC station from xbox360 used directly captured audio from emulation.

Hello, can you add the ability to change bloom in the game? I always disable it, because it seems to me that the game looks better without it, bloom is in the visualSettings.dat file in common/data and in TBoGT/common/data, open it with notepad, and you can find these lines
misc.BloomIntensityClamp.HD 10
misc.BloomIntensityClamp.SD 10.00

and so, you just need to change these values 10 and 10.00, you can add this in game in the settings screen.

There is also a misc.BloomIntensityClamp.SD.ps3 5.00 but this is most likely not used in the PC version.t this is most likely not used in the PC version.
