### ISSUE TITLE
[Feature Request] Console Blood Drops/stains

### ISSUE THREAD

**Issue by SandeMC** [ThirteenAG/GTAIV.EFLC.FusionFix#137]
On consoles, there's blood drops/stains on the screen when you get shot
[YouTube clip with the effect](https://youtube.com/clip/Ugkx_xNKEQVwh0KPlzznjhwbT-jxeNusC5OV)
Xbox Rain Droplets rather just makes blood "droplets" on the screen, so that's not really the effect I want. I also couldn't find any mod restoring the original effect.

**Comment by sTc2201** [comment]
The "console" blood screen effects are present on PC as well, so I'm not sure what you mean exactly with "original" or "console" effect, they look identical too me.

**Comment by SandeMC** [comment]
"present on PC as well" but they're not?

**Comment by sTc2201** [comment]
Maybe show proof they don't exist, are broken or whatever then?

From my video it looks pretty clear that the effects do exist on PC, they are not as vibrant though, because I didn't crank up the saturation like the person did in the video clip you posted.

https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/41953894/0a02fbb8-0a63-4559-88a5-24480cc319eb

**Comment by Tomasak** [comment]
But they do seem darker on PC

**Comment by Tomasak** [comment]
someone made comparison with same time and weather between console and pc and its all same and present, unless OP means something else
