### ISSUE TITLE
[Feature Request] Include various minor fixes

### ISSUE THREAD

**Issue by SandeMC** [ThirteenAG/GTAIV.EFLC.FusionFix#147]
I'm not sure if any of those are already included, but I'll leave them for consideration anyway. They're scattered online, so it'd be nice if one mod just implements them all. Of course, you probably should ask permissions from mod devs- I'm merely listing them.

- [Fixes from Responsive Plus and Graphics Fix](https://drive.google.com/file/d/13OgDDm0xakbdRONPlrnN5zRfshdAgwhd/view) - you can read the [details here - at the responsive plus section](https://pastebin.com/uZFXACsu) + TBoGT splash effects into base IV
- [Fixed LCPD Buffalo](https://www.gtainside.com/en/gta4/cars/181342-fixed-lcpd-buffalo/)
- [Player Outfit Texture Fixes](https://gtaforums.com/topic/925011-player-outfit-texture-fixes) - Partially rejected, but has versions that don't affect .rpf's
- [Fixed Suit Display in Perseus](https://gtaforums.com/topic/984565-iv-fixed-suit-display-in-perseus/)
~~[Dodgy Doc - Higher Quality; Liberty Ferry Terminal - Waiting Sign Fix; Sugar Chomps - Separate Signs](https://gtaforums.com/topic/974798-donnits-bakery/)~~ - Rejected: "could be integrated into various fixes"
~~[Default Pistol Iron Sight Fix](https://www.nexusmods.com/gta4/mods/15)~~ - Rejected: "would be better part of varios fixes"
~~[Luis' Helmet Reflection Fix](https://www.gtainside.com/en/gta4/skins/125863-luis-s-helmet-reflections-fix/)~~ - Rejected: "anything playerped.rpf related: big no, as there is no good way to replace it without breaking other mods."
~~[Luis' Bag Texture Fix](https://www.gtainside.com/en/gta4/skins/136118-luis-s-bag-texture-fix/)~~ - Rejected: "anything playerped.rpf related: big no, as there is no good way to replace it without breaking other mods."
~~[Johnny's Shoe Texture Fix](https://www.gtainside.com/en/gta4/skins/125196-johnny-s-shoe-texture-fix/)~~ - Rejected: "anything playerped.rpf related: big no, as there is no good way to replace it without breaking other mods."
~~[Traffic Cops: Back in Toolbooths](https://www.gtainside.com/en/gta4/mods/187365-traffic-cops-back-in-the-tollbooths/) - they show up on missions, but not in freeroam - supposedly they should~~ - Included in v1.89
~~[Menu Art Fix](https://gtaforums.com/topic/887527-ash_735s-workshop/page/5/#comment-1072165611)~~ - Rejected

**Comment by Tomasak** [comment]
ad first one: those are mostly design choices rather than bugs, maybe the cargpr fixes could be shipped with FF, rest could be integrated into various fixes or console visuals
ad second same here
ad third: if author allows, or is remade for ff, it could be added
ad anything playerped.rpf related: big no, as there is no good way to replace it without breaking other mods.
ad menu art: ye wont ship prolly with ff, could be linked on some HQ art place like with ash's stuff on main page on gtaf.
ad traffic cops: there is some bug in tlad based on description but could be added.
ad pistol: would be better part of varios fixes too

too bad fusion fix shipped with fixed cars, but i dont want personally clutter it with more fixed models. Bawsaq sign will be removed in next update as its more of a workaround and proper fix will be done

**Comment by SandeMC** [comment]
For Player Outfit Texture Fixes, there's versions for Peds and NOOSE fix, those could be included as they're .img modifications.
For Traffic Cops - I personally had it work fine with files, using corresponding files and everything.

Of course, feel free to judge yourself what should be included. I just figured, since FusionFix already includes .img fixes, it wouldn't hurt to have more minor fixes. I'll let Attramat know about Pistol Iron Sight and Fixes from RP and GF.

**Comment by Tomasak** [comment]
>What about Luis' and Johnny's fixes, aswell as Suit Display Fix?

ad anything playerped.rpf related: big no, as there is no good way to replace it without breaking other mods.
>For the second one - what about Sign Fix?

as i said, i various fixes would be better place for it

>For Traffic Cops - I personally had it work fine, using corresponding files and everything.

"In TLAD they may show up looking weird due to unfinished ped work by R*, so you might want to get a mod to replace, or use GTA IV ones over 'em."
so idk about this one
