### ISSUE TITLE
Enabling console shadows will disable night shadows 

### ISSUE THREAD

**Issue by MehranAkbarii** [ThirteenAG/GTAIV.EFLC.FusionFix#192]
Enabling console shadows will disable night shadows

**Comment by MagicAl6244225** [comment]
It makes a trade.  Xbox 360/Playstation 3 features shadows cast by vehicles under streetlights. Unmodded PC does not have that. Unmodded PC headlights cast shadows, console does not have that. Rockstar disabled the vehicle shadows to do the headlight shadows because of bugs, both features can't be on at the same time.

FusionFix lets you choose. Whether this is a good trade is up to you, but we note the choice of vehicle shadows without headlight shadows how most versions of GTAV do it (360/PS3,XB1/PS4,PC except at highest settings).

**Comment by suyash691** [comment]
We can have an option to force it on like we do in zolikapatch (albeit the tradeoff being potential bugs, specially when not using dual headlight option).

**Comment by SandeMC** [comment]
@Tomasak is this planned to be fixed?

**Comment by Tomasak** [comment]
As MagicAl said, its intended behaviour, When someone comes up with better way to deal with all the shadows shenanigans we have to stick with this.
