### ISSUE TITLE
The game is considerably more demanding with FusionFix versions after 1.80

### ISSUE THREAD

**Issue by Markie98** [ThirteenAG/GTAIV.EFLC.FusionFix#235]
Apologies if this is not much of a reason to open an issue here as it should probably be expected.

FusionFix releases newer than 1.80, so 1.94, 1.96, and 2.0, give me about 25% higher GPU usage with the INI settings that are shared between different versions as well as the in-game graphics settings being kept the same, even when there's no discernible visual difference.

I'm reporting this because it could potentially be due to some sort of oversight or bad configuration rather than purely visual improvements or fixes in which case I thought it would be really worth it looking into.

**Comment by RecklessGlue540** [comment]
It's really an issue with the renderer at this point. Use DXVK for better resource management (If it actually improves anything).
Not much of a reason to point it out, simply because it's very well known already, and a full fix for it is not feasible (rewriting the renderer of the game... it's obvious).

**Comment by ThirteenAG** [comment]
v1.96 should run much slower than v2.0. With 2.0, there's a loss of performance due to how z-fighting fix works, shadows configuration/quality and maybe other shader related things. I've compared original files performance and with the fix, there's no significant difference. It could be at certain places though, and with different pc specs/game settings.

**Comment by justdumbgamer** [comment]
Is it just me? Swimming in the water causes massive frame rate drops.

**Comment by wmrichard** [comment]
Regarding this, is there a some information available which setting of fusion fix are the most demanding or what their performance impact is, so we can set them lower or disable them completely. Espesially helpful for Steam Deck users.

**Comment by bkdwt** [comment]
The difference here with Fusion installed and not installed is very notable. My CPU is a i7 8700 and the temperatures go absolute HIGH using this mod. 

DXVK solves this question, but the FPS drops a little bit.

**Comment by SandeMC** [comment]
@Tomasak I think this could be set to unplanned? Game runs fine with vanilla options, and I don't think there's much else that can be done to performance.

**Comment by Markie98** [comment]
Yeah, it seems like it's mostly just a byproduct of ShaderFixesCollection (which is now part of FusionFix as FusionShaders) restoring/fixing/improving visual aspects of the game making it generally more demanding especially on the GPU side, unfortunate but only natural.

**Comment by SandeMC** [comment]
If you disable all FusionFix features, you get identical to vanilla performance.

**Comment by Markie98** [comment]
Doesn't seem to be the case here.

**Comment by Mondea** [comment]
I'm having a similar issue. Fresh GTA IV Complete edition install + DXVK v2.2 allows me to play 5120x2880 at 90FPS. Adding FusionFix drops performance down to barely 60FPS at 4K.  Also when only using DXVK, the GPU usage in MSI afterburner is fluctuating, but around 30-50%. With FusionFix, it gets capped at 100%

Running on a Lenovo Legion 5 Pro 3070 12700H with the game on the display connected directly to HDMI (dGPU)

**Comment by MagicAl6244225** [comment]
This sounds like it's because FusionFix scales visual effects to have full intensity at resolutions and the vanilla game does not. On vanilla these effects look as intended only at 720p console resolution and get weaker as you increase resolution. It takes more GPU to calcuate these effects at higher resolutions.

If you imagine a small live theater with one fog machine filling the stage with fog, but then the show moves to a stage three times bigger, you would need at least three fog machines. Vanilla has one fog machine no matter how big the stage is. FusionFix adds more fog machines when you get a bigger stage. But they're not free, you're gonna pay for that dry ice and electricity. With FusionFix you can set Distant Blur to a lower setting to reduce the added blur.

To compare FusionFix to vanilla without these scaled effects making such a difference, measure vanilla with Definition On, and measure Fusion Fix with Shadow Filter on any setting that's not PCSS, Console Shadows off, Depth of Field off, Motion Blur off, Definition on Extra, and Anti-aliasing Off. Make sure your Night Shadows settings are the same in both, either off or Medium (higher than Medium doesn't look any different).

Another performance tip is to never use Very High shadow quality. High looks almost the same and is a lot faster.

**Comment by RecklessGlue540** [comment]
> This sounds like it's because FusionFix scales visual effects to have full intensity at all resolutions and the vanilla game does not. On vanilla these effects look as intended only at 720p console resolution and get weaker as you increase resolution. It takes more GPU to calcuate these effects at higher resolutions.
> 
> If you imagine a small live theater with one fog machine filling the stage with fog, but then the show moves to a stage three times bigger, you would need at least three fog machines. Vanilla has one fog machine no matter how big the stage is. FusionFix adds more fog machines when you get a bigger stage. But they're not free, you're gonna pay for that dry ice and electricity. With FusionFix you can set Distant Blur to a lower setting to reduce the added blur.
> 
> To compare FusionFix to vanilla without these scaled effects making such a difference, measure vanilla with Definition On, and measure Fusion Fix with Shadow Filter on any setting that's not PCSS, Console Shadows off, Depth of Field off, Motion Blur off, Definition on Extra, and Anti-aliasing Off. Make sure your Night Shadows settings are the same in both, either off or Medium (higher than Medium doesn't look any different).
> 
> Another performance tip is to never use Very High shadow quality. High looks almost the same and is a lot faster.

And another performance and fix tip is to use the Console Lamppost models with the PC Wall light models.

**Comment by Mondea** [comment]
> This sounds like it's because FusionFix scales visual effects to have full intensity at all resolutions and the vanilla game does not. On vanilla these effects look as intended only at 720p console resolution and get weaker as you increase resolution. It takes more GPU to calcuate these effects at higher resolutions.
> 
> If you imagine a small live theater with one fog machine filling the stage with fog, but then the show moves to a stage three times bigger, you would need at least three fog machines. Vanilla has one fog machine no matter how big the stage is. FusionFix adds more fog machines when you get a bigger stage. But they're not free, you're gonna pay for that dry ice and electricity. With FusionFix you can set Distant Blur to a lower setting to reduce the added blur.
> 
> To compare FusionFix to vanilla without these scaled effects making such a difference, measure vanilla with Definition On, and measure Fusion Fix with Shadow Filter on any setting that's not PCSS, Console Shadows off, Depth of Field off, Motion Blur off, Definition on Extra, and Anti-aliasing Off. Make sure your Night Shadows settings are the same in both, either off or Medium (higher than Medium doesn't look any different).
> 
> Another performance tip is to never use Very High shadow quality. High looks almost the same and is a lot faster.

Thanks for the explanation and tips. I haven't compared to vanilla without DXVK, but I know what I get with it and there isn't a setting I can change for FusionFix that makes it much better. I tried your suggestions, and perhaps gained a few FPS, but as you've explained, its likely caused by the metaphorical fog machine.

**Comment by Tomasak** [comment]
Several optimization was done later on. Sadly some of the new graphical features might be resource heavy especially on lower end computers. It is recommended to disable DOF, AA, tone down shadow settings in graphics menu and disable DynamicShadowForTrees in FusionFix ini
