### ISSUE TITLE
DLSS, DLAA, FSR2 as an anti-aliasing alternative?

### ISSUE THREAD

**Issue by CuddleBear92** [ThirteenAG/GTAIV.EFLC.FusionFix#379]
### What should happen

With the new addition of more AA options, would it be possible to get the best option out atm? 
DLSS and DLAA? 
Guess adding [Nvidia StreamLine](https://github.com/NVIDIAGameWorks/Streamline) would cut the process down if something like FSR and XeSS where planned. 
Would give users a cleaner image and lower end hardware can run the game faster in the end. 

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
It's nice and all, I definitely agree.
But GTAIV is not like the new games. It uses ancient technologies and therefore TAA, FSR and other things like that are not possible because of DirectX9 limitations. Not even MSAA is possible which is the preferred method of reducing aliasing.

DLSS and DLAA in addition to the things said above, needs Nvidia's and Rockstar's approval. Which cannot happen.

This issue can be closed.

**Comment by KoKlusz** [comment]
It's not Impossible, but it does require manually adding motion vectors to the game like PureDark's DLSS 3 mod for GTAV

**Comment by RecklessGlue540** [comment]
> It's not impossible, but it does require manually adding motion vectors to the game, like PureDark's DLSS 3 mod for GTAV.
> 
> It would also probably need a conversion layer build in, but you shouldn't be really running GTA IV without DXVK anyway these days.

I don't think conversion layers such as DXVK are able to do this...
And like I said, DLSS / DLAA is something only Rockstar and Nvidia might be able to do (since DLSS is proprietary stuff), unfortunately only on a newer rerelease of the game with newer tech. 

Anyway, this was discussed before here, https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/issues/21 and not even the most basic things like FSR1 or probably even Contrast Adaptive Sharpening can be achieved with the tech limitations we currently have.

**Comment by KoKlusz** [comment]
> I don't think conversion layers such as DXVK are able to do this... 

I mention conversion layer since FSR2 is DX12/VK only IIRC, so the game would need to be converted from DX9 first in order for it to work. Dunno if DXVK by itself would be enough, probably not, I was just thinking out loud.

>And like I said, DLSS / DLAA is something only Rockstar and Nvidia might be able to do (since DLSS is proprietary stuff), unfortunately only on a newer rerelease of the game with newer tech.

PureDark made a business out of adding DLSS SuperRes/FrameGen to games that don't have them natively, there are also a few others modders that do that. NV is well aware about this and haven't raised any actions to counter that, in fact the main DLSS guy said he was surprised it's even possible. That said, almost all of those mods are for games that already support DLSS or/and FSR2. The only exception is GTAV, where PureDark said he had to manually patch the game shaders to add motion vectors. So again, it is possible (at least for games supporting DX11 and up) and NV and R* doesn't seem like an obstacle here, but in the case of GTAIV I assume that lack of native support for modern API is the biggest roadblock.

> Anyway, this was discussed before here, [Parallellines0451/GTAIV.EFLC.FusionShaders#21](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/issues/21) and not even the most basic things like FSR1 or probably even Contrast Adaptive Sharpening can be achieved with the tech limitations we currently have.

Alas.

**Comment by Tomasak** [comment]
Several AA options have been implemented. If it will be possible, more will come, but nothing is promised
