### ISSUE TITLE
Game crashes when hanging from ledge

### ISSUE THREAD

**Issue by limussb** [ThirteenAG/GTAIV.EFLC.FusionFix#417]
### Game version this happens in

v1.2.0.59

### What area of the game

When Niko hangs from a ledge, it freezes breifly before instantly booting me to desktop. This is only happening when I have Fusionfix, when I removed it, it didn't crash.

### What should happen

The game should not be crashing and booting me to desktop.

### CrashDumps and logs

[GTAIV.exe.20240121002312.log](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/files/14000585/GTAIV.exe.20240121002312.log)

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
Just posting log is not enough, crash dump is needed. Also remove all img archives inside update folder and test again.

**Comment by limussb** [comment]
The crash dump is a megabyte too big for me to post it in a GitHub reply. Is there anyway for me to send you the crash dump another way?

I’ll try removing the img archives in the morning as well. Thank you

**Comment by limussb** [comment]
https://drive.google.com/file/d/189zaABHTW-jiSpnjNLWMDYZz474tUwXl/view?usp=drive_link

Here's the dump, I'm sending it through a google drive link. Thanks again for your help.

**Comment by ThirteenAG** [comment]
Access denied.

**Comment by limussb** [comment]
My bad, try again now. I just gave access

**Comment by ThirteenAG** [comment]
Just like other reports, nothing in this points to fusion fix. You have quite a lot of other plugins, can you install a clean game separately, then try to reproduce with fusion fix alone? If it works, then it needs to be pinpointed which mod or plugin is causing potential conflict.

**Comment by limussb** [comment]
I found the issue, turns out one of the animations got corrupted by a different mod so I removed that. thanks for your help.

**Comment by ThirteenAG** [comment]
Can you post what mod is that?

**Comment by rsm86** [comment]
Sorry to revive this, but I'm having the same issue. I've cleaned up all my mods and started off with Fusion Fix fresh, no other mods, and I still get the crash when hanging off ledge (as soon as I remove fusion fix, I no longer get this crash). This doesn't even have to be in any mission. As soon as Niko hangs from any sort of ledge, game hangs (audio continues for a few seconds) and then crash to desktop with no other error messages, which is the same behavior I think @limussb experienced. I created a dump from the exe file but it is around 1.8 gb. I can post it if needed but seeing as how this has been reported numerous times, not sure if it is any help. Are there people who are able to play the game without this problem? I love Fusion Fix, but sadly I can't progress any further in the game due to this bug (currently on the LJ mission where you have to chase a dealer through some alleyways and at one point you have to climb over a fence and it induces this crash).
