### ISSUE TITLE
Can't change new FF settings individually, they all change to the same option at the same time across graphics, display,controls

### ISSUE THREAD

**Issue by Karso2024** [ThirteenAG/GTAIV.EFLC.FusionFix#495]
### Game version this happens in

v1.2.0.59

### What area of the game

No matter what I try (this version or downgrade) in the  graphics and display & controls settings when I press any of the new bottom options they all change at the same time to the same thing across display/control/graphics settings (the new added stuff) . So yeah for some reason I can't change any setting individually. 
For example Change shadow filter to on -> console shadows, antialiasing, fpslimiter all change to on + motionblur, bloom ,consolegamma, screenfilter, depth of field, treefx, definition all change to on + raw input, always run, cover centering change to on. It's either all on, all off, all custom, all default, all IV, all TLADT, all TBOGT across the new settings in graphics, display & controls. Normally control settings like always run can only be on or off but when I put shadow filter on TLADT always run (and raw input,cover) also change to TLADT. 
I can go in the game, but I don't know if any of the FF are actually applied.

Some more info: Rockstar launcher version but it also happened with downgrade to 1.8
windows 10, Sapphire Nitro+ Radeon RX580 8gb, Adrenalin 24.3.1, AMD ryzen 5 1600 6 cores 12 threads, 16gb ram, gigabyte AB350 Gaming 3 - bios F52n

### What should happen

What could cause this? What could fix this?

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by ThirteenAG** [comment]
> What could cause this?

Asi is not loaded.

> What could fix this?

Open asi with https://github.com/lucasg/Dependencies and check what you're missing. Likely a directx redist.

**Comment by ThirteenAG** [comment]
The file in system32 won't be loaded by the game because it's 64 bit. You need to install the redist.
https://www.microsoft.com/en-us/Download/confirmation.aspx?id=35

**Comment by Karso2024** [comment]
Tried that but I get the message there is already a newer or equal version of DirectX installed. Installation not needed.

**Comment by ThirteenAG** [comment]
Then try offline installer, the needed file is clearly missing.
https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by Karso2024** [comment]
extracted, did the setup directx runtime installation (search for edited directx runtimeparts and may edit. Installed. And then the problem is still there. Thoughts?

I saw in a topic below (fusionfix settings problem #483 ) that more people have the same problem and its from V 2.0 onwards but V 1.96 works apparently. Could it be a fusionfix problem? Or is it from our end? Really want to figure this out, driving me crazy.

**Comment by ThirteenAG** [comment]
It's not a fusion fix problem, like I said you don't have all required files:
![image](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/4904157/6cfb78af-369b-4862-b953-60451a6f69bc)
Once you have d3dx9_43.dll in `C:\Windows\SysWOW64\D3DX9_43.dll`, it should work.

Why installing these redistributables doesn't work for you I don't know, try googling missing d3dx9_43.dll for other possible solutions.

**Comment by RecklessGlue540** [comment]
Maybe try installing this too?
https://github.com/abbodi1406/vcredist/releases
Download the x86_x64.exe.

**Comment by Karso2024** [comment]
Installed also checked C:\Windows\SysWOW64\D3DX9_43.dll the file is there... still not working.

![2024-06-11 16_44_57-](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/assets/172356920/9bb44f2b-f9ed-4156-8ef3-a38d753fbe78)

I installed 1.96 (like the guys from the other topic) and that is working properly... so the question is why is that version working and the later ones not?

**Comment by ThirteenAG** [comment]
Because 1.96 doesn't require D3DX9_43.dll.

If the file is present on disk, then it can't be loaded for some other reason. From what I can tell, I have D3DX9_43.dll with size 2345kb in System32 folder, in SysWOW64 the size is 1952kb. You have 64bit dll in SysWOW64, which doesn't make any sense.

**Comment by Karso2024** [comment]
Ah that explains. Last thing I could try is replacing the D3DX9_43's with yours?

**Comment by ThirteenAG** [comment]
I'd advise to properly figure out what prevents dx redist from installing correctly.

[D3DX9_43.zip](https://github.com/user-attachments/files/15791580/D3DX9_43.zip)

**Comment by Karso2024** [comment]
Somehow that worked :D 
You are my hero! Thx a lot

**Comment by botcheese999** [comment]
Getting the exact same behavior described here (all new menu options — TreeFX/TreeLighting, Distant Lights, Tree Alpha, ScreenFilter, ConsoleGamma — linking to the same/wrong value regardless of what's set individually). Adding some data points since my setup differs slightly from the other reports:

Setup: GTA IV Complete Edition downgraded to 1.0.8.0 via ZolikaPatch (backwards compatibility mode, ASI loader renamed to xlive.dll as recommended in #500), running the exe shipped by IVTweaker (patched on top of the ZolikaPatch base). FusionFix is fully up to date, d3d9.dll/vulkan.dll/update/GTAIV.EFLC.FusionFix all confirmed matching hash/date with the latest release zip.

Ruled out so far:

D3DX9_43.dll — confirmed present in SysWOW64, correct 32-bit build, ~1952KB (matches the size mentioned in this thread as correct). Reinstalling the DirectX End-User Runtime reports it's already up to date, no change.
Hybrid GPU driver mismatch (NVIDIA dGPU + AMD iGPU on a Ryzen laptop) — updated AMD Adrenalin drivers fully, no change.
DXVK vs native Vulkan renderer (Graphics API toggle) — identical corrupted values in both.
Reinstalling FusionFix clean over a fresh, mod-free install — no change.
Manually editing the [MISC] block in the ini (ConsoleGamma/DistantBlur/TreeLighting/ScreenFilter) — values get silently overwritten back to garbage (e.g. TreeLighting=7, which is out of the documented 0-2 range for "PC"/"PC+"/"Console") on next launch or exit. Deleting those 4 lines entirely causes an immediate freeze+crash on load instead of regenerating them cleanly.

Visually this manifests as jagged/torn alpha-test edges on all foliage map-wide (screenshot available if useful), plus nonsensical labels in the Display menu (Distant Lights showing radio station/gamemode names instead of a valid value).

Happy to provide logs or test anything else — this seems specific to the downgraded/CE-with-old-patch scenario rather than a mod conflict, given how many other variables have been ruled out.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/45586409-f6b2-49fd-a9e2-4a5da5ce9731" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/1cef6b12-32f9-4793-9eaa-6ef2e8a256a9" />
