### ISSUE TITLE
Vehicle's engine sound plays with a delay

### ISSUE THREAD

**Issue by Degrees9871** [ThirteenAG/GTAIV.EFLC.FusionFix#538]
### What should happen

Not sure if this isn't a vanilla bug but maybe it may be addressed here.
Basically in some cars engine sounds start working after 1-2 min drive. Using latest patch.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
That usually happens when you increase the vehicle budget, but can also happen with the vanilla game.

It is caused by the increased vehicle variety and hence the amount of different vehicle sound banks loading at one time, causing certain vehicles to lose their sounds until the memory gets freed. 

I doubt anything can be done to fix this, but I'd suggest 120mb being the highest vehicle budget value you should ever use, I personally don't get the issue THAT much with this value.

**Comment by Degrees9871** [comment]
got it
