### ISSUE TITLE
Problem with Trees when using TreesFX: PC+ function in new FF 3.0.0

### ISSUE THREAD

**Issue by inzeRT-G0LD** [ThirteenAG/GTAIV.EFLC.FusionFix#549]
In the new version of FF 3.0.0 there are many different settings and other innovations that have improved the performance of the game in many ways (unlike previous versions of FF), and also really improved the perception of the game - just WOW.......

But now one minus has appeared, namely: when using TreesFX PC+ setting, trees do not change visually, as if only slightly (at the slightest viewing).
I don't know of course, maybe this was done because work is underway on this tree shader, so that in the future it will be possible to use Normal and Specular textures, I don't know?!!

Nevertheless, I would like to clarify why this is now happening with trees when using PC+

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Parallellines0451** [comment]
Several vanilla tree models have either bad baked AO or none whatsoever, so "PC+" was adjusted to look better with them and to be more faithful to the original look. Its main purpose now is to fix the intense orange glow under the trees in some lighting conditions (e.g. vanilla sunny weather at 09:00).

Normal and specular support won't be added to gta_trees because that would require tree models to be edited, otherwise they'd crash the game. A better idea would be to create a custom tree shader with normal, spec and AO, if someone shows interest in making trees specifically for it.

**Comment by OfficialDayL** [comment]
> Several vanilla tree models have either bad baked AO or none whatsoever, so "PC+" was adjusted to look better with them and to be more faithful to the original look. Its main purpose now is to fix the intense orange glow under the trees in some lighting conditions (e.g. vanilla sunny weather at 09:00).
> 
> Normal and specular support won't be added to gta_trees because that would require tree models to be edited, otherwise they'd crash the game. A better idea would be to create a custom tree shader with normal, spec and AO, if someone shows interest in making trees specifically for it.

We already have multiple different custom vegetation packs with different shader options, since a shader with trees, spec, normal isn't a thing unfortunately. I made options that uses the cutout shader, but comes with leaf specular textures and another version with tree shaders to have wind effects, but leaf speculars are gone. I would really appreciate a shader that combines the tree shader with normal and specular options, so I would be more than thankful for something like that.

Feel free to check the vegetation packs with the options I've mentioned:
GTAV vegetation: https://mega.nz/file/BMRTQZxI#l9Uka6YXzQ0aCKQPqAqNFyvmPox7nXkZ2vRnScFAfeg
RDR2 vegetation: https://mega.nz/file/1MwhWJ5K#njvHu0fw4jL5qfp6uA1954t7bncGTAtLCmhHc_QIxYE
RDR2 Autumn vegetation: https://mega.nz/file/JJwyETJa#nZs3uxz-4prq6qDoi9b_Y8yLT8m4wM3k1rmLBw1zlew

I would love to create an option that uses tree, specular and normal all together. There's also an improved stock vegetation pack by BisonSales that could also benifit from that. I would also adjust that pack then.

**Comment by Parallellines0451** [comment]
@OfficialDayL 

I'll do it later then, though an apology for the disparaging comments in your community that a couple of my friends showed me would be nice.

**Comment by Parallellines0451** [comment]
[gta_trees_extended.zip](https://github.com/user-attachments/files/16639919/gta_trees_extended.zip)

There, gta_trees, but with AO, normal and specular support. Let me know if that works.

OpenIV syntax should be: `gta_trees_extended.sps texturesampler specularfactor specularcolorfactor specmapintmask bumpiness bumpsampler specsampler`

[ShaderManager.txt](https://github.com/user-attachments/files/16639944/ShaderManager.txt)

**Comment by inzeRT-G0LD** [comment]
> [gta_trees_extended.zip](https://github.com/user-attachments/files/16639919/gta_trees_extended.zip)
> 
> There, gta_trees, but with AO, normal and specular support. Let me know if that works.
> 
> OpenIV syntax should be: `gta_trees_extended.sps texturesampler specularfactor specularcolorfactor specmapintmask bumpiness bumpsampler specsampler`
> 
> [ShaderManager.txt](https://github.com/user-attachments/files/16639944/ShaderManager.txt)

I tried it and it seems: IT WORKS!!!

It's very cool, at least for me it is! But there are probably more competent experts in terms of the appearance of trees, who may offer to refine the shader, adjust it, etc.

But a lot of what I need is already showing itself as it should!!! The trees began to look colorful, voluminous, and so on!

**Comment by Parallellines0451** [comment]
Good to hear. It should have the same behavior as gta_normal_spec in terms of lighting.
If you or @OfficialDayL decide to use it for your mods, I'll include it in FusionFix.

**Comment by inzeRT-G0LD** [comment]
> Good to hear. It should have the same behavior as gta_normal_spec in terms of lighting. If you or @OfficialDayL decide to use it for your mods, I'll include it in FusionFix.

Yes! It definitely needs to be turned on, because now, with this shader, even the most vanilla, outdated GTA4 trees can look quite great!

**Comment by Parallellines0451** [comment]
> It definitely needs to be turned on

I mean it doesn't do anything by itself, tree models need to be re-exported and made to use it. Just to clarify, you did that when you tested it, correct?

**Comment by inzeRT-G0LD** [comment]
> I mean it doesn't do anything by itself, tree models need to be re-exported and made to use it. Just to clarify, you did that when you tested it, correct?

Well, of course, of course!

I spent a long time and tediously rewriting the vegetation.odr files for gta_trees_extended.sps

Moreover, I am still doing this, but for other vegetation models (I am just experimenting, looking at how different tree models work with this shader)

**Comment by Briangomez8** [comment]
Sorry for my lack of knowledge, but how did you manage to make it work like before.

I tried copying the shaders to the common folder and adding the commands you said to ShaderManager but it didn't work :(

**Comment by Parallellines0451** [comment]
@Briangomez8 

Just copy the  gta_trees_extended section from the ShaderManager.txt file I sent to the actual ShaderManager.xml from OpenIV.

Then, follow this template for the models: `gta_trees_extended.sps texturesampler specularfactor specularcolorfactor specmapintmask bumpiness bumpsampler specsampler`

Example: `gta_trees_extended.sps Diffusepath 0.1 0.1 1.0;0.0;0.0 0.1 Normalpath Specpath`
