### ISSUE TITLE
The in my opinion disappointing 3.0.0 update. We have to talk about it.

### ISSUE THREAD

**Issue by OfficialDayL** [ThirteenAG/GTAIV.EFLC.FusionFix#554]
### What should happen

I was really looking forward for all the new changes from 3.0.0, since months. Especially the godrays + the better performance I always heard about, just to be heavily dissapointed by the result of the update, when it finally came out. I just ignore all the crashes, game not launching issues and other headache issues I had with 3.0.0, since I'm using patch 1.0.8.0 and you guys will probably just say that everything below CE isn't compatible, which is honestly bullshit, since 2.5.6 and everything before worked fine, but I feel like both sides would just waste time here, since you guys are obviously not interested to optiminize this mod for lower patches, but there are a lof of things that aren't related to the patch, but overall to the mod itself.

First of all removing PCSS shadows and SSAA was a huge mistake and a really weird decision in my opinion. I know there are people who are too stupid to know what these options are doing, so they just enable stuff and then complain about bad performance. But why do I have to suffer, because of that? I love PCSS shadows and I have a really good GPU (RTX 3070), so my PC can handle it. Also, why are wire shadows removed? Overall shadows seem less impressive looking now. Definitely a huge downgrade in my opinion. I can understand that performance optimization is an important part, but removing features or decreasing the look of visuals like that shouldn't be an option and is honestly... kinda lazy I have to say. At least keep these options hidden inside the .ini or something for people who still want it. That would be heavily appreciated by a lot of people probably, since I'm surely not the only one complaining about this.

I love FusionFix a lot and it's definitely an essential mod at this point, but I can't enjoy 3.0.0 at all, due to the mentioned issues from above, which is why I reverted back to the 2.5.6 version. Something that I will also recommend to other users in the future, if they want to install my mods in combination with FusionFix. I feel kinda forced to do that, since FF 3.0.0 doesn't seem to work properly on lower patches anymore + the other issues I personally have with the new version.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by ThirteenAG** [comment]
> why do I have to suffer, because of that

Because the world doesn't revolve around you, who are you even? You want these features, fork, implement and Pull Request in a way that is compatible with the current code base. I won't read the rest until you do just that. Many people contributed to that last release, some even coded for the very first time. And you just cry and complain without a single crash dump, crash log.

>  I'm using patch 1.0.8.0

> and you guys will probably just say that everything below CE isn't compatible

> which is honestly bullshit

> I just ignore all the crashes, game not launching issues and other headache issues I had with 3.0.0

So which is it? Is it compatible and working perfectly, or not compatible and that's why you have crashes, issues and whatnot?

**Comment by Tomasak** [comment]
1) open source, feel free to contribute
2) i don't see any receipt from you about paying anyone on team to be your code monkey
3) it works on clean preCE version installed from dvd or steam cmd download, just because it doesn't work on frankensteined downgrade copy is user's fault. Maybe try clean game and add one by one mod instead of throwing ff 3.0 on downgraded copy with 3 cracks, 4 asi loaders and 10 closed source ™ mods

**Comment by OfficialDayL** [comment]
> 1. open source, feel free to contribute
> 2. i don't see any receipt from you about paying anyone on team to be your code monkey
> 3. it works on clean preCE version installed from dvd or steam cmd download, just because it doesn't work on frankensteined downgrade copy is user's fault. Maybe try clean game and add one by one mod instead of throwing ff 3.0 on downgraded copy with 3 cracks, 4 asi loaders and 10 closed source ™ mods

I guess you don't understand what the issue section is there for. I just told you guys what issues I have with this mod. This is literally what this section is there for, so stop complaining.

**Comment by OfficialDayL** [comment]
Non of this was any helpful by the way, so thanks for wasting my time.

**Comment by ThirteenAG** [comment]
> > Because the world doesn't revolve around you, who are you even? You want these features, fork, implement and Pull Request in a way that is compatible with the current code base. I won't read the rest until you do just that. Many people contributed to that last release, some even coded for the very first time. And you just cry and complain without a single crash dump, crash log.
> 
> So you're basically admiting to ignore obvious issues then. The whole answer is a pure shizo moment lol. That was definitely the last time that I try to communicate with you in any way. Best support ever. Thumbs up.

I don't have any issues. Post a crash dump, from latest game version, and then we'll talk.
As for shadows, the code for both new shadows and PCSS in the shaders repo, if you figure out how to make them work, feel free to pull request. Only 300 shaders to edit, looking forward to your first contribution. SSAA is very basic functionality of any graphics vendor, the one that was in fusion fix is redundant and "hacky". Still, the code for it is in the previous commit, feel free to adapt it with the current code base and pull request. Good luck!

**Comment by Tomasak** [comment]
> Non of this was any helpful by the way, so thanks for wasing my time. If you guys always act like this it doesn't surprise me that this mod is such a mess.

Only one wasting anyones time here is you wasting ours. You demand help yet you can't even do bare minimum of giving crashdump.

**Comment by OfficialDayL** [comment]
> > > Because the world doesn't revolve around you, who are you even? You want these features, fork, implement and Pull Request in a way that is compatible with the current code base. I won't read the rest until you do just that. Many people contributed to that last release, some even coded for the very first time. And you just cry and complain without a single crash dump, crash log.
> > 
> > 
> > So you're basically admiting to ignore obvious issues then. The whole answer is a pure shizo moment lol. That was definitely the last time that I try to communicate with you in any way. Best support ever. Thumbs up.
> 
> I don't have any issues. Post a crash dump, from latest game version, and then we'll talk. As for shadows, the code for both new shadows and PCSS in the shaders repo, if you figure out how to make them work, feel free to pull request. Only 300 shaders to edit, looking forward to your first contribution. SSAA is very basic functionality of any graphics vendor, the one that was in fusion fix is redundant and "hacky". Still, the code for it is in the previous commit, feel free to adapt it with the current code base and pull request. Good luck!

No thanks. I definitely have no interests to work with such an aggressive person. It's your mod, so why should I fix the issues/problems/downgrades you guys have created? Makes no sense. Also, not everyone who creates mods can automatically code, but you guys can, so. Whatever. It's not like you guys are any interested to get into these issues anyways. I'll just stay on 2.5.6 and you guys can continue with whatever you guys are doing. Bye.

**Comment by ThirteenAG** [comment]
>  I definitely have no interests to work with such an aggressive person.

Nobody is forcing you to, but you come here, start calling me schizo and whatnot, and I'm the one that's aggressive. Cool cool.

> It's your mod, so why should I fix the issues/problems/downgrades you guys have created?

If it's my mod, why should I care about anything you say then? You are a real piece of work, huh.

> I'll just stay on 2.5.6

v1.96 better. Use that instead. Also downgrade the game to v1.0.2.0, v1.0.8.0 is too new.

**Comment by Parallellines0451** [comment]
@OfficialDayL

Zero features were removed because of performance, apart from one that caused crashes and was actually an unintended addition in previous versions (double resolution shadows). The only reasons for something to be removed are if it causes visual glitches, if it's redundant, if it's unstable, or if there's something better.

Here are some examples:
- SSAA: caused problems with bloom and depth of field scaling, required a game restart, and required more code to maintain and worry about. VSR or DSR do the same job more easily and without issues.
- PCSS: caused cutoff penumbras when they became too large, because IV's subpar CSM implementation makes [calculating a proper size](https://postimg.cc/Z0XFGkp4) almost impossible, so they had to be very subtle in previous versions. Pretending that shadows looked better in previous versions doesn't make sense when everything else about them is significantly improved; especially bias, filtering and view distance.
- "Improved" definition: is redundant because it only affects grass and fences. So the other two modes were renamed to Off/On.
- 256 tile stipple: console code was restored, which produces better looking results, and is also the same as GTA V.
- Tree AO: removed from "PC+" tree lighting because both vanilla and console trees have terrible baked AO, and it isn't FF's job to fix that. I'd make a custom tree shader with AO, normal and spec support, but no one has shown interest in using it for their mods.
- Specular tweaks: caused more problems and inconsistencies than they fixed, only a massive asset overhaul could deal with the problem properly.
- In-game shadow softness adjustment: was replaced with more granular ini settings (ShadowSoftness & ShadowBias), but since that was more difficult for people to understand than I expected, it'll make a return in a small update later.
- Foam: it never worked, and I don't think I need to explain that one any further.
- Wire shadows: were never a part of FF apart from one specific version from even before 2.0 because they make wires use deferred rendering, so they become extremely aliased, so it was immediately reverted. It's just flipping a 1 to a 0 in gta_wire.sps.

3.0 has the largest list of fixes and improvements to date, but just because you don't understand how something works, it doesn't mean that it's useless; and just because you choose to ignore bugs that were present in previous versions, it doesn't mean that they weren't there. If you actually wanted to see the mod improve you'd communicate properly instead of saying things behind our backs, like a significant portion of the IV modding community does instead of actually trying to cooperate. This kind of behavior is why the game stayed broken for almost an entire generation.

It's extremely demotivating to see people focusing on one or two things that had to be severely limited and barely worked, which were then removed because of that, instead of even once mentioning all the other dozens of things that were added or improved. Even more so when they say "I feel like this was better" without actually showing anything, or without doing a side by side comparison themselves and focusing on the details that matter.

I'm the sole person maintaining the native shaders of FusionFix. That's my passion project and I put a lot of work and care into it, even though I'm just an amateur programmer at the end of the day, and I do it all for free because I believe that's how modding should be. I'm tired of being attacked constantly either because of old senseless drama I never even had anything to do with, or because people don't understand something and don't care to communicate to see it changed, or to have an insight on why it's changed.

![oldshadows](https://github.com/user-attachments/assets/4868cf91-940d-4fb9-a9c2-ecb1b1cfac90)
![image](https://github.com/user-attachments/assets/f2b2f4d8-f584-4c9d-8a31-4975086b6dc4)
![356807471-7a963672-44f0-4e45-bd0d-22e60add38df](https://github.com/user-attachments/assets/107955dd-a79e-4302-a43e-0902df326c1d)

**Comment by ThirteenAG** [comment]
> Even more so when they say "I feel like this was better" without actually showing anything, or without doing a side by side comparison themselves and focusing on the details that matter.

Let's add PCSS toggle that does nothing, I'm prepared to bet that people like OP will not even notice. They just find something else to complain about, instead of making code.

**Comment by ChunkLeChuck** [comment]
I should probably stay quiet, but as someone who has talked with @OfficialDayL a lot and also uses 1080 because of IVSDK.NET I am not disappointed in this update. I  appreciate DayL, but I think he went a bit too hard at you guys. 

It's true that older patches don't get the same amount of attention as CE, but I think we have come to expect this already. It is also true that some of us had some crashing issues out of the box with FF 3.0.0 but I view it as a challenge personally and I just need to rebuild my modded game like many times before. I've come to expect a certain amount of jank from GTAIV and after a big update it is not something that surprises me.
That being said, the mod itself works on 1080/1070 so it's not like it's not supported at all.

Now let me say that I didn't have much chance to try out FF 3.0.0 but it's clear that a HUGE amount of work went into this update and the passion especially from the shader and graphics improvement side of things is clearly palpable.

I have  big respect for @Parallellines0451 because I think what he managed to pull out of this broken PC port (with the help of others of course) is magic. After you came into the scene FusionFix positively got transformed into a must have mod. 

Now I read the replies here and  I  appreciate the technical breakdown of the whole PCSS debacle and I trust that the removal was not easy but instead we got some controls over shadows like we didn't have before and also we can customize godrays via the .ini so theres is still a lot of control in the user's hand when it comes to the presentation.

One tiny thing  that I miss is the wire shadows still, in the previous version of FF one could just flick ExtraDynamicShadows = 3 in the ini and it would draw shadows for them, but I understand if this had to go for the sake  of maintaining stable graphics.

All in all basically I just wanted to say thanks to Para here coz I don't really get the chance elsewhere.  

FF 3.0.0 because it's a huge update  is a bit of a transition, but I think we will manage.

**Comment by juicermv** [comment]
In all honesty, this entire thread and this type of feedback is not super appropriate for GitHub Issues. 
I wish FF had a public Discord server where we could discuss these things directly and calmly, provide direct feedback to the amazing team working on this mod, and just have a proper place for the FF community.

**Comment by OfficialDayL** [comment]
@Parallellines0451 First of all, thank you for taking time to explain things as detailed as possible. I respect and appreciate that a lot. You and another person that I don't want to involve into this explained the most issues I have instead of commenting useless answers like @ThirteenAG and @Tomasak did. I'm a direct person and I honestly admit that my post could be a bit nicer, but I wasn't insulting or impulsive with my first post, while they directly started answering stuff like "Because the world doesn't revolve around you, who are you even?" or "i don't see any receipt from you about paying anyone on team to be your code monkey". I admit that I can't take criticism well neither and that I'm also pissed sometimes, when users complain about stuff, but this is just insane and in my opinion there's nothing you can say to defend this.

Of course I don't have the same technical understanding as you guys do, but in my opinion that's why it's the responsibility of you guys to communicate things properly like you did now, so people with less technical understanding can comprehend why you guys decided to remove certain stuff. All I knew was that stuff was broken, because of performance reasons, which doesn't really explains much. Maybe you guys did exlained this somewhere already, but I haven't found anything or anyone talking about it, so of course I assume that there's no proper explanation then, which is why I made this post. A huge suggestion: If you guys decide to remove certain features, please make sure to explain in the changelog why you guys did that, so users can understand the reason, even without being Mark Zuckerberg.

I didn't meant to disrespect you, even if some of the mentioned things are created from you. I didn't even realized it, even if it makes sense, since you work on shader stuff all the time. This is nothing personal and nothing against you as a person. You should know that I respect you and that I appreciate your shader work you did over the years a lot. Unfortunately I must admit that I can't deal with some of the people you're working with, but that's not your problem and I hope you're capable to separate this, because I'am.

Since I say everything on a public community server I totally expect that there's a high chance that people from the FF team will notice what I or other people say there, so from my perspective I don't talk behind anyone's back, but you're allowed to see this differently of course. Everyone from the FF team is welcomed to join my Discord Server, if they feel attacked by any messages, so they can confront me or others. It's a public place with free speech and not a secret society or something like that.

Again, thank you for your time and for clearing things up. I understand that my worries about the shader related stuff was unnecessary thanks to your explanations. Sorry for my lack of understanding. You're doing a good job with the work you're doing, since years.

**Comment by Parallellines0451** [comment]
> That being said, the mod itself works on 1080/1070 so it's not like it's not supported at all.

Yes. The "version wars" are especially tiring. Just install the mod in the latest official version of the game, or at the very least downgrade said official version properly before jumping into conclusions. If there's a problem, open an issue and describe it in as much detail as possible, include pictures and a crash dump, and make sure that no other mods are involved.

> A huge suggestion: If you guys decide to remove certain features, please make sure to explain in the changelog why you guys did that.

That's a fair point, even if it was previously explained at least twice in separate issues opened here. Truth is, there were so many new things this time that even compiling them all into a single changelog was a challenge.

I also have a couple suggestions for you and others: communicate if there's a problem, as I previously mentioned, instead of not doing that and then telling people to not use the mod; and don't drag the whole mod and team through the mud if you have a problem with one or two people involved with it.

> I wish FF had a public Discord server where we could discuss these things directly and calmly, provide direct feedback to the amazing team working on this mod, and just have a proper place for the FF community.

> Everyone from the FF team is welcomed to join my Discord Server, if they feel attacked by any messages, so they can confront me or others. It's a public place with free speech and not a secret society or something like that.

I appreciate the suggestion and invite, but I'm personally not interested in being part of any GTA IV modding communities, including the forums, as I think I've seen enough of them already. However, I'm open to Discord friend requests to talk about about graphics and shaders more in depth at "parallellines" to the best of my ability.

> Now I read the replies here and I appreciate the technical breakdown of the whole PCSS debacle and I trust that the removal was not easy

Robi did what was possible with the knowledge available and limitations at hand, so yes, the most difficult part for me (as it was my decision) wasn't even the removal of the feature by itself, but also the fact that a dear friend had made it. As I said, I'm far from being a graphics expert, but if there's a way to work around the specific quirks of the CSM implementation, I'll bring it back.

> In all honesty, this entire thread and this type of feedback is not super appropriate for GitHub Issues.

Yes, moving on.

> One tiny thing that I miss is the wire shadows still, in the previous version of FF one could just flick ExtraDynamicShadows = 3 in the ini and it would draw shadows for them, but I understand if this had to go for the sake of maintaining stable graphics.

Not exactly. That only works for wires that don't use gta_wire (and ideally they all should use it because of [this](http://www.humus.name/index.php?page=3D&ID=89)). While changing the gta_wire.sps drawbucket does enable shadows for wires that use it, it disables the anti aliasing functionality and causes extreme aliasing on them, which is especially visible on the Broker bridge cables.

ExtraDynamicShadows = 3 actually should have been removed long before 3.0 because not all objects are meant to cast shadows for various technical and artistic reasons, and it caused several bugs obviously, as it's a very naive way of doing things. 1 and 2 work by selectively overriding IDE flags on safe objects that have specific keywords in them (like "fence", "grate", "bush" etc.).

If you think that any props (including wires) could cast shadows without causing issues, check by editing their IDE flags to enable shadow casting and post pictures of them and their filenames in a separate issue.

Anyway, I hope we're done here and everything is cleared up. Talk to me on Discord if you want further details.

**Comment by MOnkeMan5009** [comment]
> @OfficialDayL
> 
> Zero features were removed because of performance, apart from one that caused crashes and was actually an unintended addition in previous versions (double resolution shadows). The only reasons for something to be removed are if it causes visual glitches, if it's redundant, if it's unstable, or if there's something better.
> 
> Here are some examples:
> 
> * SSAA: caused problems with bloom and depth of field scaling, required a game restart, and required more code to maintain and worry about. VSR or DSR do the same job more easily and without issues.
> * PCSS: caused cutoff penumbras when they became too large, because IV's subpar CSM implementation makes [calculating a proper size](https://postimg.cc/Z0XFGkp4) almost impossible, so they had to be very subtle in previous versions. Pretending that shadows looked better in previous versions doesn't make sense when everything else about them is significantly improved; especially bias, filtering and view distance.
> * "Improved" definition: is redundant because it only affects grass and fences. So the other two modes were renamed to Off/On.
> * 256 tile stipple: console code was restored, which produces better looking results, and is also the same as GTA V.
> * Tree AO: removed from "PC+" tree lighting because both vanilla and console trees have terrible baked AO, and it isn't FF's job to fix that. I'd make a custom tree shader with AO, normal and spec support, but no one has shown interest in using it for their mods.
> * Specular tweaks: caused more problems and inconsistencies than they fixed, only a massive asset overhaul could deal with the problem properly.
> * In-game shadow softness adjustment: was replaced with more granular ini settings (ShadowSoftness & ShadowBias), but since that was more difficult for people to understand than I expected, it'll make a return in a small update later.
> * Foam: it never worked, and I don't think I need to explain that one any further.
> * Wire shadows: were never a part of FF apart from one specific version from even before 2.0 because they make wires use deferred rendering, so they become extremely aliased, so it was immediately reverted. It's just flipping a 1 to a 0 in gta_wire.sps.
> 
> 3.0 has the largest list of fixes and improvements to date, but just because you don't understand how something works, it doesn't mean that it's useless; and just because you choose to ignore bugs that were present in previous versions, it doesn't mean that they weren't there. If you actually wanted to see the mod improve you'd communicate properly instead of saying things behind our backs, like a significant portion of the IV modding community does instead of actually trying to cooperate. This kind of behavior is why the game stayed broken for almost an entire generation.
> 
> It's extremely demotivating to see people focusing on one or two things that had to be severely limited and barely worked, which were then removed because of that, instead of even once mentioning all the other dozens of things that were added or improved. Even more so when they say "I feel like this was better" without actually showing anything, or without doing a side by side comparison themselves and focusing on the details that matter.
> 
> I'm the sole person maintaining the native shaders of FusionFix. That's my passion project and I put a lot of work and care into it, even though I'm just an amateur programmer at the end of the day, and I do it all for free because I believe that's how modding should be. I'm tired of being attacked constantly either because of old senseless drama I never even had anything to do with, or because people don't understand something and don't care to communicate to see it changed, or to have an insight on why it's changed.
> 
> ![oldshadows](https://private-user-images.githubusercontent.com/133058741/358218892-4868cf91-940d-4fb9-a9c2-ecb1b1cfac90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MTUwNzMsIm5iZiI6MTcyNDYxNDc3MywicGF0aCI6Ii8xMzMwNTg3NDEvMzU4MjE4ODkyLTQ4NjhjZjkxLTk0MGQtNGZiOS1hOWMyLWVjYjFiMWNmYWM5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQxOTM5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjcwODI1NzNlYTg0ODI5MWI5YzVlZjZiYmZhZmNlM2VkZTA5YTRlMjNhMTc2MWU2OTM2MzNmNzhkODIzNzdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KhSScrLnN2wxIcManMoR7NZ1En1-FYCfP1Rk__VyAfw) ![image](https://private-user-images.githubusercontent.com/133058741/358218934-f2b2f4d8-f584-4c9d-8a31-4975086b6dc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MTUwNzMsIm5iZiI6MTcyNDYxNDc3MywicGF0aCI6Ii8xMzMwNTg3NDEvMzU4MjE4OTM0LWYyYjJmNGQ4LWY1ODQtNGM5ZC04YTMxLTQ5NzUwODZiNmRjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQxOTM5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTgyOGNiZjUxMWI0NzBmMjRiOTEyNDVkOTllNWZkMTI0NGVhYjczZDFhMGExNGQ5MGNjYjhmODcxMWZjNjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2auME7s0i_2f50DmKr7IN7NXscEmxIKnB5O7ztIuF28) ![356807471-7a963672-44f0-4e45-bd0d-22e60add38df](https://private-user-images.githubusercontent.com/133058741/358219855-107955dd-a79e-4302-a43e-0902df326c1d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MTUwNzMsIm5iZiI6MTcyNDYxNDc3MywicGF0aCI6Ii8xMzMwNTg3NDEvMzU4MjE5ODU1LTEwNzk1NWRkLWE3OWUtNDMwMi1hNDNlLTA5MDJkZjMyNmMxZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQxOTM5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWM4OWZkNjAyOGZjNjEzYWJjNGM5MTRjZmQ1MmUzOWM1OTA5ZDUwODZmYmM5NDljYjYyNDlhZjYwZWNjMjJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bFLnMu3zMvE-QwRnLFUY2tnuM_xltgvqgNOZpzsHvRs)

I think fusionfix is cool and all and it finally made GTAIV the way it was supposed to be, but pls dont give up on it n shit just because of some words from someone, like dont quit like zolika did or something. too many be butthurt and give words lot of significance. I still choose to stay with 2.5.6 for the time being but i still want to see fusionfix fully fixing and making this game best it can be with everything brought back or made the way it was supposed to

**Comment by MOnkeMan5009** [comment]
> > why do I have to suffer, because of that
> 
> Because the world doesn't revolve around you, who are you even? You want these features, fork, implement and Pull Request in a way that is compatible with the current code base. I won't read the rest until you do just that. Many people contributed to that last release, some even coded for the very first time. And you just cry and complain without a single crash dump, crash log.
> 
> > I'm using patch 1.0.8.0
> 
> > and you guys will probably just say that everything below CE isn't compatible
> 
> > which is honestly bullshit
> 
> > I just ignore all the crashes, game not launching issues and other headache issues I had with 3.0.0
> 
> So which is it? Is it compatible and working perfectly, or not compatible and that's why you have crashes, issues and whatnot?

No offense, but the first part about "the world doesn't revolve around you" bruh... I get some were either unoptimized or some shit, my PC is plenty powerful to run this game smoothly at 4k..but thats besides the point, the point is that customizability is always welcomed and should be there. I mean imagine if gta 6 had to have its graphics heavy downgraded because ps4 players wanted it on that console....See the weirdness? I mean that just because some users complain that they cant run max settings shouldnt be a reason. Its like a pentium user asking for RDR2 to run good at max settings. Rockstar should downgrade cos of that?...

**Comment by ThirteenAG** [comment]
And 3.0 is a massive upgrade over 2.0, so what are you talking about even?

**Comment by MOnkeMan5009** [comment]
> And 3.0 is a massive upgrade over 2.0, so what are you talking about even?

im talking that the reply with  "the world doesn't revolve around you" was bad. I said that performance concerns shouldnt be the sole reason for a removal just because x and y cant run it at 200 fps. I didnt say the 3.0 update was bad or didnt come with anything.

**Comment by ThirteenAG** [comment]
> > And 3.0 is a massive upgrade over 2.0, so what are you talking about even?
> 
> im talking that the reply with "the world doesn't revolve around you" was bad. I said that performance concerns shouldnt be the sole reason for a removal just because x and y cant run it at 200 fps. I didnt say the 3.0 update was bad or didnt come with anything.

Are you talking about removal of PCSS? As far as I can tell, it wasn't removed, the shadow implementation was made with different approach entirely, and with that new implementation there's simply no way to make PCSS. @Parallellines0451 can correct me if I'm wrong. At some point there was an option to have very high quality shadows which I really liked, but it was never made into any release. Essentially if you feel like something was removed just for the sake of it, feel free to discard all @Parallellines0451's work and make your own. Just pointing fingers at somebody and saying this was done poorly won't make anybody drop everything and make it better *for you*. That's the point of GitHub, I don't make these releases to appeal to a larger audience, it's strictly "what can I do to enjoy this game more personally". And since I'm not a graphics programmer, I fully trust @Parallellines0451 to make these kind of decisions when it comes to shaders, shadows, and everything graphic related.

**Comment by MOnkeMan5009** [comment]
> > > And 3.0 is a massive upgrade over 2.0, so what are you talking about even?
> > 
> > 
> > im talking that the reply with "the world doesn't revolve around you" was bad. I said that performance concerns shouldnt be the sole reason for a removal just because x and y cant run it at 200 fps. I didnt say the 3.0 update was bad or didnt come with anything.
> 
> Are you talking about removal of PCSS? As far as I can tell, it wasn't removed, the shadow implementation was made with different approach entirely(think of it like this, vanilla shaders were taken and rewritten in a certain way with pcss, then for 3.0 release, vanilla shaders were taken and rewritten in a different way), and with that new implementation there's simply no way to make PCSS. @Parallellines0451 can correct me if I'm wrong. At some point there was an option to have very high quality shadows which I really liked, but it was never made into any release. Essentially if you feel like something was removed just for the sake of it, feel free to discard all @Parallellines0451's work and make your own. Just pointing fingers at somebody and saying this was done poorly won't make anybody drop everything and make it better _for you_. That's the point of GitHub, I don't make these releases to appeal to a larger audience, it's strictly "what can I do to enjoy this game more personally". And since I'm not a graphics programmer, I fully trust @Parallellines0451 to make these kind of decisions when it comes to shaders, shadows, and everything graphic related.

yeah, sure, i agree, but what i talked about and the guy above was just about the features shouldnt be removed due to a performance loss, not the other stuff lol
i think the guy above, previously, he misunderstood, and his feelings got the best of him perhaps..
