### ISSUE TITLE
Massive pop in issues with maxed sliders as of Fusion 3.0

### ISSUE THREAD

**Issue by RecklessGlue540** [ThirteenAG/GTAIV.EFLC.FusionFix#595]
### Game version this happens in

v1.2.0.59

### What area of the game

Fusion 2.5.6, dx9, only -availablevidmem in commandline, High Texture Quality, 100 View and Detail Distance:

https://github.com/user-attachments/assets/9ac060bb-9b25-4fa9-ad16-d5df1eac168b

FusionFix 3.0.5, dx9, only -availablevidmem in commandline, High Texture Quality, 100 View and Detail Distance:

https://github.com/user-attachments/assets/4b1022df-bc95-4224-9465-7302b8fd6064

Gets mitigated using -nomemrestrict in commandline but strangely only on High Texture Quality.

Seems to keep happening with DXVK as well, same exact behavior.

It's mostly the buildings that pop in quite aggressively, although it's not so bad that the map starts to vanish, which means streaming issues. Just aggressive culling or something, looks quite similar to the 360 version, however here it's worse, since you tend to move the camera faster with the mouse :p 

### What should happen

The game offers those options, and while they're not recommended to be used by normal means (unless for example you're benchmarking the game) they should at least be able to be used without extra issues.
And ideally the game should be fully stable without the user needing to touch the commandline at all (apart from availablevidmem if vram is reported wrongly)
The vanilla game and even FF 2.5.6 had no such issue even without -nomemrestrict.

### Last working version

v2.5.6

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by Ash-735** [comment]
There's a reason the warnings were put there, para was able to restore the smooth fading of the console version but sadly it only works at those specific settings or lower because this game just has to have issue with everything. Running with max sliders causes the game to do a lot of rendering of things that arn't even visible and that's why performance tanks.

**Comment by GTAIVTESTER** [comment]
I agree with you I have the same Issue, and that is the biggest reason why I use v2.5.6

**Comment by Parallellines0451** [comment]
This one is interesting. It's not related to object fading fixes or anything, rather it's an ancient bug that went unnoticed until now.

The vanilla game has a bug where draw distance settings aren't applied properly until you open the graphics menu at least once. FF added a [workaround](https://gtaforums.com/topic/934545-fusionfix/page/2/#comment-1070884189) for this that sort of "opens" the graphics menu once in the background automatically.

Vanilla:
![Screenshot (128)](https://github.com/user-attachments/assets/7812117b-0336-4e68-acf8-b4dd0f8ab4ed)
Vanilla after opening the menu once (sliders maxed):
![Screenshot (129)](https://github.com/user-attachments/assets/35eae64b-db25-4548-b99d-1981f27d9b8c)

But it turns out that the vanilla game has another bug where if you open the graphics menu at least once, you get a lot of pop-in, at least with maxed sliders. Using -nomemrestrict seems to deal with that issue.

> The vanilla game and even FF 2.5.6 had no such issue even without -nomemrestrict.

Vanilla has no pop-in in that particular spot you showed until you open the graphics menu once and it actually applies the slider values you set (because otherwise they'd be much lower than you actually think). The bug is absolutely there, just disguised.

With all versions of FF, including 2.5.6, the bug is there by default because it actually applies the slider values you set automatically. From our testing, if you really want to use maxed sliders, you need -nomemrestrict. In theory, we could ship a version with that parameter enabled to get around it, if it doesn't have any adverse side effects.

Regardless and needless to say, anything over the suggested values will cause problems and is not recommended.

**Comment by GTAIVTESTER** [comment]
> we could ship a version with that parameter enabled to get around it, if it doesn't have any adverse side effects.
yes please release a version that able us to use` -nomemrestrict` again

**Comment by Parallellines0451** [comment]
@RecklessGlue540
Yeah it seems like nomemrestrict only works with High texture quality, so there are more internal checks.

Anyway, no point in maxing out the sliders without maxing out texture quality first (and no point in maxing out the sliders in the first place).

@GTAIVTESTER 
Nothing stopping you from using a commandline, nothing changed.

**Comment by GTAIVTESTER** [comment]
I still have pop-in even with  -nomemrestrict , I haven't pop in with  -nomemrestrict in FF 2.5.6 or Vanilla

**Comment by RecklessGlue540** [comment]
If you launch the Complete Edition from Steam or RGL make sure to put your parameters inside the launch option fields from Steam, or RGL. 
For some reason the commandline.txt way does not work anymore, perhaps the latest RGL update broke it.

**Comment by GTAIVTESTER** [comment]
Got it, thanks 🫶

**Comment by GTAIVTESTER** [comment]
Still having pop-in issue with max sliders even with FF 3.0.9 with it's **ForceNoMemRestrict** and steam and RGL and commandline.txt commanline args 

my using args:
`-rglLanguage=en-US
-width 3840
-height 2160
-norestrictions -nomemrestrict
-availablevidmem 3072.0 
-forcehighqualitymirrors
`

**Comment by RecklessGlue540** [comment]
Try not to use any other useless commandlines. Specifically that last one, -norestrictions and -nomemrestrict since the commandline is now forced in FF's code.

Also do not put a .0 at the end of availablevidmem if you're on CE, useless as well.

Just use these:
-availablevidmem 3072 (or the max amount of your GPU memory, it doesn't hurt at all, both approaches work, although 2gb is enough anyways)
-width and -height for your res

And leave FF's .ini to do it's work. Hopefully.

**Comment by GTAIVTESTER** [comment]
@RecklessGlue540 
Problem still persist even with your instructions, this issue should be **reopened** at current stage because vanilla game it self hasn't this issue, but anyway I stick to FF2.5.6, until when FF team consider this as their mod issue and do something to fix it. 

anyway thank you very much for your time , effort and your responses and sorry if I bothered you but I had to report it.

**Comment by Parallellines0451** [comment]
> because vanilla game it self hasn't this issue

I just explained how it does, and 2.5.6 has it too. Try actually reading what I said in the posts above.

Nomemrestrict prevented delayed streaming for me and several other people, I can't reproduce your problem.

**Comment by GTAIVTESTER** [comment]
> > because vanilla game it self hasn't this issue
> 
> I just explained how it does, and 2.5.6 has it too. Try actually reading what I said in the posts above.
> 
> Nomemrestrict prevented delayed streaming for me and several other people, I can't reproduce your problem.

OK, I will stick to FF2.5.6 because low sliders annoying me specially low detail distance, maybe it is just my personal preference and other guys ok with with recommended stuff

**Comment by ThirteenAG** [comment]
Nobody knows/understands the problem you're having.
