### ISSUE TITLE
SHADOWS, SHADOWS,SHADOWS !!!

### ISSUE THREAD

**Issue by Adas8812** [ThirteenAG/GTAIV.EFLC.FusionFix#601]
### What should happen

Why every time an update is released - something related to shadows is affected. EVERY TIME!!! 

Example, 3.5 update had night shadows cast by npc vehicle headlights and said shadows would be visible on Niko if he where to stand in front of a car with It's headlights on. But 3.6 disabled this because "this causes bugs "... How, where?! Please, provide examples, explanation for this change and not just a simple "causes bugs, so It's disabled"...

Same stuff with that awesome PCSS option. One update It's there and the next: gone, disabled... Same reason "causes bugs "... Again, where, why?!! Why then include this shadow option in the first place...

I'm sorry, but this stuff is at times - beyond ridiculous.

This fusionfix is either a PC/console combo where the idea is to make the pc version into xbox 360, or try and fix and use all the high-end pc features that were broken since day one. At least let us choose between the two.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
> Example, 3.5 update had night shadows cast by npc vehicle headlights and said shadows would be visible on Niko if he where to stand in front of a car with It's headlights on. But 3.6 disabled this because "this causes bugs "... How, where?! Please, provide examples, explanation for this change and not just a simple "causes bugs, so It's disabled"...

This is necessary to keep the 8 max dynamic shadows limit in check, if that limit is bypassed, shadows completely start flickering and freaking out, is that what we want? Besides, not even GTAV has those shadows.
By the way, to clarify, the shadow of Niko in headlights isn't actually that alone. It's actually that every car can cast headlight shadows, which hopefully you can understand that is not right at all, and pretty wasteful if you ask me, and was clearly brought in by a lack of attention from Rockstar Toronto's side, because as I mentioned, not even GTAV has headlight shadows for every vehicle in sight, because of engine limitations involving the amount of active dynamic shadows on the screen at one time.
So "it's necessary to avoid bugs" is right in this case and imo it's justified. Maybe GTAV has a higher limit, but the thing you mentioned is still disabled there, but in the case of IV, this limit was lowered to 8 active shadows as of patch 1060 and I think it's right to disable such a thing in favor of avoidance of extra bugs.

For PCSS, you got all the reasons of it's removal [here](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/554#issuecomment-2291281565) or [here](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/512). Keeping opening issues questioning why in my opinion is a waste of time at this point. If Para can find any way to work around the game's engine limitations, he admitted he'll bring it back.
I personally don't mind it's removal at all, at least everything else about shadows is indeed better at this point, we have options to tweak softness to our liking, bias, even their base resolution multiplier, and now even for night shadows, their draw distance etc. I'm personally grateful enough.

That said update 3.0.6 is actually a bit buggy when it comes to the new headlight shadows toggle, however I'll report all the issues in a separate issue as soon as I could.

**Comment by Adas8812** [comment]
Thanks for the explanation.
