### ISSUE TITLE
[Feature Request] Internal Rendering Resolution Option for Down-sampling for Better AA

### ISSUE THREAD

**Issue by VXsz** [ThirteenAG/GTAIV.EFLC.FusionFix#624]
### What should happen

It would be great if there's a way to change the internal rendering resolution to something higher than native that gets down-sampled (internal as in; the HUD and UI elements are unaffected). This is great for both way better AA and GPU utilization which get wasted most of the time. 

For example, my GPU usage is around %40 at 120 FPS, I feel like the GPU could easily render the game internally at 5k and higher. Down-sampling is great and basically the best AA if you have the resources, and the game barely uses any (because it's barely optimized) so it'd a great addition, and with SMAA on top it would be insane.

The aliasing in this game is pretty weird as well, not sure why the game looks funky and far objects seem aliased and graphically behave weirdly, kinda wonder why. I looked around with different keywords, nothing seems like this has been discussed.

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by Parallellines0451** [comment]
Just use AMD VSR or Nvidia DSR.

**Comment by VXsz** [comment]
> Just use AMD VSR or Nvidia DSR.

Yes, these are options but they aren't great. The UI and text wouldn't be sharp, and the Bicubic scaler used by Nvidia isn't the best for shimmering. It would be great to have the option. Not sure how feasible it is tho.

**Comment by RecklessGlue540** [comment]
For what it's worth FusionFix used to include native SSAA, but it was removed because it caused several effect scaling issues, like in the vanilla game.

Trying to spend resources and time when VSR or DSR exist and work correctly in that regard isn't really a great idea and would also make things more complex to maintain I guess.

Is a scaled up UI really that much of a problem though? Maybe, but all other effects actually scale properly. I find it a fair trade off tbh.

Oh and tbf that native SSAA that was removed was also quite a bit more demanding than usual. Also required a restart to take effect and a lot of people turned it on without knowing what it is or that it didn't take effect, since it required a restart lol.
