### ISSUE TITLE
Lampost night self shadow

### ISSUE THREAD

**Issue by Adas8812** [ThirteenAG/GTAIV.EFLC.FusionFix#628]
### What should happen

Nightime lampost shadow effect is amazing (on other objects) but it doesn't cast a shadow behind it self. The picture has all nightime shadows disabled (I know that), but the point is that even when night time shadows ar enabled the lampost doesn't cast one. 
![20241002_005045](https://github.com/user-attachments/assets/563bddc9-57ef-4e94-8ca4-da6a7ed2b72d)

### Checklist

- [X] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [X] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by RecklessGlue540** [comment]
Any lights from pc/data/maps/props/roadside/lamppost.img do not cast night shadows of themselves anymore, because just take a look at the original unpatched game. Do they look right for lampposts? Not really, they're [artifacted](https://private-user-images.githubusercontent.com/133058741/346004015-a1abd46f-1bbf-458e-8da3-5c69e4e10445.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MjA0OTgsIm5iZiI6MTcyNzgyMDE5OCwicGF0aCI6Ii8xMzMwNTg3NDEvMzQ2MDA0MDE1LWExYWJkNDZmLTFiYmYtNDU4ZS04ZGEzLTVjNjllNGUxMDQ0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQyMjAzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzVkNzc4OTk2MDAyYjBjMmQwNGEyMGJiNWNjNDcwZTllYTMyZTMxMzE4NzFhNjNiNzE4NGQ2YjhjN2Y2YmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xqs3UzGVZNDKU97UpBQL4k3YiQfaMMjPKlY5J_qjEJo), due to the technique Rockstar used for those type of shadows, which is imprecise, because the technique was never meant to be used for outdoor artificial lights, and only in interiors. 

Rockstar Toronto enabled all models from said .img archive on PC to cast shadows without altering any piece of the original game's code to make the projection of these shadows proper. 

The Fusion guys have found a smart way to get rid of only the bugged shadows by making every lamppost model use a shader set that includes emissive lighting without sacrificing normal map specular map or cubemap support. 
Emissive lighting basically makes any model that has it applied unable to cast night shadows, getting rid of only the buggy and ugly self shadows in this case.

If you want a more in depth explanation of the other issues of Night Shadows (because this isn't the only one and there are plenty), check this [post](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/issues/41#issuecomment-2210347721).

The goal of FusionFix is to fix critical issues of the PC port that make it inferior to console, while not fixing anything that was never intended by the original devs of the game, such as these erratically enabled shadows. So don't expect any more fixes for those shadows and even then calling these fixes is kind of incorrect, as they're pretty much workarounds at the end of the day.

The only real solution to all these bugs is to use Lamppost Shadows Off and profit. It will still maintain these shadows in interiors, where they were always intended.

**Comment by MagicAl6244225** [comment]
We intentionally removed lamppost self-shadowing because the game cannot self-shadow objects that contain a light source correctly from all directions. In the unmodded game about half of the lampposts have a distorted self-shadow depending which way they are turned. It is fundamentally the same issue as why vehicles cannot have night shadows and headlight shadows at the same time. Other games of this era have a similar engine limitation and we copied their solution (changing the lamppost material to emissive 0).

If you really want the broken lamppost self-shadows back (when Night Shadows and Lamppost Shadows are enabled), place a copy of the game's original lamppost.img file in the update folder, renamed or put in a subfolder to come first in alphabetical priority before "GTAIV.EFLC.FusionFix".

**Comment by Parallellines0451** [comment]
PC shadow casting lampposts are wrong, and any bugs that come with them will not be fixed. Non shadow casting lampposts, like consoles, is the intended and correct behavior.
