### ISSUE TITLE
I dont want vehicle night shadows only headlights shadows for the player.

### ISSUE THREAD

**Issue by DOODBRO47** [ThirteenAG/GTAIV.EFLC.FusionFix#631]
### Game version this happens in

v1.2.0.43

### What area of the game

Here my issue. I only want headlights shadows not vehicle night shadows because they are heavy for my system basically i want someone to tell me how to enable only headlights shadows for the player not vehicle night shadows.
I have also tried 111111111 cheat in game.
I also want to show my POV.
https://youtu.be/WlFJVLLDNxE

### What should happen

I want to see player shadows in front of car headlights and not under the lamppost also no vehicle night shadows.
it was working the previous build [v3.1.0].
thank you.

### Last working version

v3.1.0 

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by RecklessGlue540** [comment]
The game is very limited and very buggy when it comes to the amount of night shadows present on the screen at once.
It's necessary to make trade offs so no issues arise from making everything cast these shadows.

To clarify, if you want the player to cast a shadow under headlights, all vehicles around you will have to cast headlight shadows. And the limit of the total night shadows is 8 at one time (at least on patches higher than 1.0.4.0). With everything casting shadows you essentially break the game, shadows will start disappearing all around depending on camera angle.

Headlight shadows were never intended by the original devs of the game and they won't be fixed any further because of that.
Furthermore lamppost night shadows weren't intended either. 
This effect was mostly intended for interiors where it worked and made sense. It doesn't work everywhere and the guys who worked on the PC port tried to enable them sort of globally just for the sake of doing it and not knowing it'd become one of the main problems of this notorious port, especially when it comes to it's performance.

Headlight shadows are way more demanding than lamppost shadows as well, because they render in a much bigger range and also render stuff which isn't visible at all (such as undergrounds).

**Comment by DOODBRO47** [comment]
im not trying to discredit your point but it used to work in the previous version of fusion fix v3.1.0 and now its doesnt i dont get it.

**Comment by Adas8812** [comment]
Yeah something similar was with PCSS shadows. One update they were there the next  - gone. 
Yes it causes problems, bugs. But why then try to make such an option in the first place if it causes issues?
I reckon people who make these mods/updates/bug fixes must check proof these things before release. 
Or is it to say  "hey the game can theoretically and  practically work with this but hey It's buggy so here's just the taster but next update will remove this ".
Bit of a rant here and I KNOW MULTIPLE PEOPLE explained to me the whole PCSS stuff but the point is not that. 
The point is why do it in the first place if it will cause issues?

**Comment by Otheucarvalho2** [comment]
> lgo semelhante foi com as sombras do PC

I watched your video is working, but the shadow of the game was disabled by the devs for causing bugs, as I understand it.

**Comment by Otheucarvalho2** [comment]
> 1111111111 cheat it doesnt seem to work for me? do i need to restart the game to make this cheat work?

I watched your video is working, but the shadow of the game was disabled by the devs for causing bugs, as I understand it.

**Comment by Tomasak** [comment]
Headlight shadows due to their buggy nature are unsupported
