### ISSUE TITLE
Invalid Resources Error When Playing Pool

### ISSUE THREAD

**Issue by william11220** [ThirteenAG/GTAIV.EFLC.FusionFix#94]
I am getting a crash with an Invalid Resources Error while attempting to play pool in the Lost MC Clubhouse, but it seems to happen also to any other pool game. It is kind of annoying, although everything else in the mod seems to work.

**Comment by sTc2201** [comment]
The modified pool game script that fixes some stuff and was shipped with FusionFix is probably only compatible with IV and overrode the pool game scripts in the episodes (TLAD & TBoGT) and most likely caused the crash.

You can fix it by moving the script into a separate **`.img`** inside a folder called **`IV`** within the **`update`** folder, that will ensure that it loads the script for IV only.

The script is called **`pool_game.sco`** and is located in **`update\GTAIV.EFLC.FusionFix\GTAIV.EFLC.FusionFix.img`**, you will need OpenIV to open the img and also create one for the IV folder.

That should be globally fixed with the next release though.

**Comment by Tomasak** [comment]
fixed
